### PR TITLE
solve the error of model and push my code in main

### PR DESCRIPTION
**Pull request by GauravKalbhor**
models not working so i do a hard reset, now the code runs fine from my side

### CODE REVIEW

**Review by contact-tarun — APPROVED** [review]

**Comment by contact-tarun** [comment]
done

**Comment by contact-tarun** [comment]
done

**Review by GauravKalbhor — COMMENTED** [review]
db.sqlite giving conflict isssue manage it with my data base
(ckeck it first the merge it )

**Comment by GauravKalbhor** [comment]
solved the db.sqlite isuee now its fine

**Pull request merged**
